# services:
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/usr/src/app
#       - bundle:/usr/local/bundle
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     environment:
#       - HISTFILE=/usr/src/app/log/.bash_history
#     depends_on:
#       - db
#       - redis
#   db:
#     image: postgres:14
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=changeme
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#   redis:
#     image: redis
#     volumes:
#       - redis_data:/data

# volumes:
#   pg_data:
#   redis_data:
#   bundle:


version: "3.8"

x-common-variables: &global-variables
  REDIS_ADDR: redis
  REDIS_PORT: 6379
  SIDEKIQ_USERNAME: admin
  SIDEKIQ_PASSWORD: password

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - "~/.ssh/:/.ssh"
      - "./docker/dev/database.yml:/app/config/database.yml"
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      <<: *global-variables
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_live
    expose:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - "./docker/dev/setup_database.sh:/usr/local/bin/setup_database.sh"
  redis:
    image: redis:latest
    restart: unless-stopped
  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: ./docker/dev/Dockerfile
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
  #   volumes:
  #     - .:/app
  #     - bundler_gems:/usr/local/bundle/
  #   depends_on:
  #     - db
  #     - redis
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     <<: *global-variables
volumes:
  bundler_gems:
  db:
    driver: local
